// TexasGTM — Seed 65+ verified Russia B2B leads
// Run: node scripts/seed-leads.js
const fs = require('fs');
const path = require('path');
const { Pool } = require('pg');

const envPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, 'utf8').split('\n').forEach(line => {
    const m = line.match(/^(\w+)=(.+)$/);
    if (m) process.env[m[1]] = m[2].trim();
  });
}

const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });

function dedupKey(name, domain) {
  return (name || '').toLowerCase().replace(/[^a-zA-Zа-яА-Я0-9]/g, '') + ((domain || '').toLowerCase().replace(/[^a-z0-9.]/g, ''));
}

const LEADS = [
  // TIER 1: ALREADY HIRING INDIAN WORKERS
  { company_name: 'Ozon (Argument LLC subcontractor)', domain: 'ozon.ru', sector: 'warehouse_logistics', priority: 'HOT', city: 'Pushkino', region: 'Moscow Region', company_size: '50,000+', pain_point: 'Already hired 70+ Indian workers via Argument LLC. 50+ warehouses across Russia all understaffed.', decision_maker_title: 'HR Director / Warehouse Operations Head', phone: '+7 495 009 0999', email: 'hr@ozon.ru', contact_method: 'Telegram DM + Email', find_instructions: 'corp.ozon.com contacts; LinkedIn: search Ozon HR директор; hh.ru employer profile', notes: 'Ask for warehouse subcontract partnership. Ozon outsources to subcontractors — pitch as one.' },
  { company_name: 'X5 Group (Pyaterochka / Perekrestok)', domain: 'x5.ru', sector: 'retail', priority: 'HOT', city: 'Moscow', region: 'Moscow', company_size: '100,000+', pain_point: 'President confirmed Indian workers hired for logistics & distribution. 15,000+ vacancies unfilled at any time.', decision_maker_title: 'Директор по персоналу / VP People', phone: '+7 495 232 1818', email: 'hr@x5.ru', contact_method: 'Email + LinkedIn', find_instructions: 'x5.ru/en/contacts; LinkedIn: X5 Group HR; hh.ru employer page', notes: 'Focus on distribution center roles.' },
  { company_name: 'Samolyot Group (Самолёт)', domain: 'samolet.ru', sector: 'construction', priority: 'HOT', city: 'Moscow', region: 'Moscow', company_size: '5,000+', pain_point: 'Launched Indian construction worker pilot program March 2025. Needs electricians, welders, general builders.', decision_maker_title: 'Operational Director / Head of Construction', phone: '+7 495 966 3300', email: 'hr@samolet.ru', contact_method: 'Email + Phone', find_instructions: 'samolet.ru/contacts; LinkedIn search Самолет Group HR', notes: 'They had language barrier issues — pitch pre-trained Russian-ready workers.' },
  { company_name: 'Za Rodinu Fish Processing (За Родину)', domain: 'zarodinukld.ru', sector: 'food_processing', priority: 'HOT', city: 'Kaliningrad', region: 'Kaliningrad Region', company_size: '500–2,000', pain_point: 'FIRST Russian company to hire Indian workers in 2024. Already has the permit framework in place.', decision_maker_title: 'Директор по персоналу / Plant Manager', email: 'info@zarodinukld.ru', contact_method: 'Phone + Email', find_instructions: 'zarodinukld.ru; VK search: За Родину рыба Калининград; 2GIS Kaliningrad', notes: 'CASE STUDY company — fastest close possible.' },
  { company_name: 'Wildberries', domain: 'wildberries.ru', sector: 'warehouse_logistics', priority: 'HOT', city: 'Moscow', region: 'Moscow', company_size: '100,000+', pain_point: 'Russia largest marketplace. Constant warehouse worker shortage. 100,000 sqm fulfillment centers.', decision_maker_title: 'Head of Mass Recruitment', phone: '+7 495 775 7575', email: 'hr@wildberries.ru', contact_method: 'Email + LinkedIn', find_instructions: 'wildberries.ru/services/trudoustrojstvo; LinkedIn; hh.ru employer', notes: 'Focus on order pickers, packers, loaders. Very high volume contract potential.' },
  // TIER 1: CONSTRUCTION
  { company_name: 'PIK Group (ПИК)', domain: 'pik.ru', sector: 'construction', priority: 'HIGH', city: 'Moscow', region: 'Moscow', company_size: '50,000+', pain_point: 'Russia largest developer. Builds 3M+ sqm/year. Chronic shortage of builders, finishers, electricians.', decision_maker_title: 'HR Director / Construction Director', phone: '+7 495 777 5757', email: 'hr@pik.ru', contact_method: 'Email', find_instructions: 'pik.ru/career; LinkedIn; hh.ru' },
  { company_name: 'LSR Group (Группа ЛСР)', domain: 'lsrgroup.ru', sector: 'construction', priority: 'HIGH', city: 'St. Petersburg', region: 'Leningrad Region', company_size: '20,000+', pain_point: 'Major SPb developer. Active sites in SPb, Moscow, Yekaterinburg.', decision_maker_title: 'HR Director', phone: '+7 812 313 9911', email: 'info@lsrgroup.ru', contact_method: 'Email', find_instructions: 'lsrgroup.ru/contacts; LinkedIn' },
  { company_name: 'Etalon Group', domain: 'etalongroup.com', sector: 'construction', priority: 'HIGH', city: 'Moscow', region: 'Moscow', company_size: '10,000+', pain_point: 'Top-5 Russian developer. Constant need for construction workers especially finishing crews.', decision_maker_title: 'Директор по персоналу', phone: '+7 495 917 8787', email: 'hr@etalongroup.com', contact_method: 'Email', find_instructions: 'etalongroup.com/en; LinkedIn; hh.ru' },
  { company_name: 'Brusnika (Брусника)', domain: 'brusnika.ru', sector: 'construction', priority: 'HIGH', city: 'Yekaterinburg', region: 'Sverdlovsk Region', company_size: '3,000+', pain_point: 'Active Ural developer. Ural region = most acute labor shortage.', decision_maker_title: 'HR Manager', phone: '+7 343 379 5151', email: 'hr@brusnika.ru', contact_method: 'Email + Phone', find_instructions: 'brusnika.ru; career page; 2GIS Yekaterinburg', notes: 'Ural region = critical shortage area.' },
  { company_name: 'GK Avtodor', domain: 'avtodor.ru', sector: 'construction', priority: 'HIGH', city: 'Moscow', region: 'Moscow', company_size: '20,000+', pain_point: 'Government road construction company. Active road building across Russia.', decision_maker_title: 'HR Director', phone: '+7 495 727 8000', email: 'hr@avtodor.ru', contact_method: 'Email', find_instructions: 'avtodor.ru/contacts; LinkedIn; hh.ru', notes: 'Government = stable long-term contract.' },
  // METALLURGY / MANUFACTURING
  { company_name: 'Severstal (Северсталь)', domain: 'severstal.com', sector: 'metallurgy', priority: 'HIGH', city: 'Cherepovets', region: 'Vologda Region', company_size: '50,000+', pain_point: 'Russia largest steel producer. Constantly replacing workers.', decision_maker_title: 'Директор по персоналу', phone: '+7 8202 53 7000', email: 'hr@severstal.ru', contact_method: 'Email + LinkedIn', find_instructions: 'severstal.com/en/contacts; LinkedIn Severstal HR; hh.ru', notes: 'Welders, metalworkers, machine operators. Very high volume.' },
  { company_name: 'NLMK (Новолипецкий МК)', domain: 'nlmk.com', sector: 'metallurgy', priority: 'HIGH', city: 'Lipetsk', region: 'Lipetsk Region', company_size: '50,000+', pain_point: 'Top steel producer. Worker shortage in plant operations.', decision_maker_title: 'HR Director', phone: '+7 4742 44 0000', email: 'hr@nlmk.ru', contact_method: 'Email', find_instructions: 'nlmk.com/en/contacts; LinkedIn; hh.ru' },
  { company_name: 'RUSAL', domain: 'rusal.ru', sector: 'metallurgy', priority: 'HIGH', city: 'Moscow', region: 'Multiple (Siberia)', company_size: '60,000+', pain_point: 'World 2nd largest aluminium producer. Siberian plants extremely hard to staff locally.', decision_maker_title: 'Head of HR', phone: '+7 495 720 5150', email: 'hr@rusal.ru', contact_method: 'Email', find_instructions: 'rusal.ru/contacts; LinkedIn; hh.ru', notes: 'Remote Siberian plants = perfect for imported labor.' },
  { company_name: 'Uralmash', domain: 'uralmash.ru', sector: 'manufacturing', priority: 'HOT', city: 'Yekaterinburg', region: 'Sverdlovsk Region', company_size: '15,000+', pain_point: 'Explicitly mentioned by Sverdlovsk Chamber of Commerce as needing Indian workers.', decision_maker_title: 'Директор по персоналу', phone: '+7 343 344 0000', email: 'hr@uralmash.ru', contact_method: 'Phone', find_instructions: 'uralmash.ru/contacts; 2GIS Yekaterinburg; hh.ru', notes: 'EXPLICITLY named in Indian worker hiring press coverage. Very warm lead.' },
  { company_name: 'Ural Wagon Zavod (УВЗ)', domain: 'uvz.ru', sector: 'manufacturing', priority: 'HOT', city: 'Nizhny Tagil', region: 'Sverdlovsk Region', company_size: '30,000+', pain_point: 'Largest rail car manufacturer. Explicitly mentioned in Indian worker hiring discussions.', decision_maker_title: 'HR Department', phone: '+7 3435 25 5000', email: 'hr@uvz.ru', contact_method: 'Phone', find_instructions: 'uvz.ru/contacts; hh.ru Nizhny Tagil', notes: 'Approach for non-sensitive roles only.' },
  { company_name: 'KamAZ', domain: 'kamaz.ru', sector: 'automotive', priority: 'HIGH', city: 'Naberezhnye Chelny', region: 'Tatarstan', company_size: '45,000+', pain_point: 'Russia largest truck maker. Giant factory complex. Workers needed at all skill levels.', decision_maker_title: 'HR Director / Head of Mass Recruitment', phone: '+7 8552 37 5555', email: 'hr@kamaz.ru', contact_method: 'Email', find_instructions: 'kamaz.ru/contacts; LinkedIn; hh.ru' },
  { company_name: 'AvtoVAZ', domain: 'lada.ru', sector: 'automotive', priority: 'HIGH', city: 'Togliatti', region: 'Samara Region', company_size: '40,000+', pain_point: 'Russia largest car maker (Lada). Workforce constantly fluctuating.', decision_maker_title: 'HR Director', phone: '+7 8482 73 5555', email: 'hr@avtovaz.ru', contact_method: 'Email', find_instructions: 'lada.ru/contacts; LinkedIn; hh.ru' },
  // MINING
  { company_name: 'Norilsk Nickel (Норникель)', domain: 'nornickel.ru', sector: 'mining', priority: 'HIGH', city: 'Norilsk', region: 'Krasnoyarsk Region', company_size: '80,000+', pain_point: 'Arctic city. Impossible to hire locally. World largest nickel producer. Pays premium.', decision_maker_title: 'Директор по персоналу', phone: '+7 495 787 7667', email: 'hr@nornickel.ru', contact_method: 'Email', find_instructions: 'nornickel.ru/contacts; LinkedIn', notes: 'Arctic location = maximum shortage.' },
  { company_name: 'Polyus (Полюс)', domain: 'polyus.com', sector: 'mining', priority: 'HIGH', city: 'Krasnoyarsk', region: 'Krasnoyarsk + Yakutia', company_size: '18,000+', pain_point: 'Russia largest gold producer. Remote Siberian sites.', decision_maker_title: 'HR Director', phone: '+7 495 641 3330', email: 'hr@polyus.com', contact_method: 'Email', find_instructions: 'polyus.com/en/contacts; LinkedIn; hh.ru' },
  { company_name: 'Alrosa (АЛРОСА)', domain: 'alrosa.ru', sector: 'mining', priority: 'HIGH', city: 'Mirny', region: 'Yakutia (Far East)', company_size: '35,000+', pain_point: 'World largest diamond producer. Essentially impossible to staff locally.', decision_maker_title: 'Head of Recruitment', phone: '+7 495 620 5555', email: 'hr@alrosa.ru', contact_method: 'Email', find_instructions: 'alrosa.ru/contacts; LinkedIn; hh.ru' },
  // CHEMICALS
  { company_name: 'PhosAgro (ФосАгро)', domain: 'phosagro.com', sector: 'chemicals', priority: 'HIGH', city: 'Cherepovets', region: 'Vologda + Murmansk', company_size: '20,000+', pain_point: 'Major chemical plant. Remote northern locations = impossible to staff locally.', decision_maker_title: 'HR Director', phone: '+7 495 232 9505', email: 'hr@phosagro.ru', contact_method: 'Email', find_instructions: 'phosagro.com/contacts; LinkedIn; hh.ru' },
  { company_name: 'SIBUR', domain: 'sibur.ru', sector: 'chemicals', priority: 'HIGH', city: 'Moscow', region: 'Moscow + Siberia', company_size: '20,000+', pain_point: 'Russia largest petrochemical company. Giant new plants under construction in Siberia.', decision_maker_title: 'Head of HR', phone: '+7 495 607 4444', email: 'hr@sibur.ru', contact_method: 'Email', find_instructions: 'sibur.ru/en/contacts; LinkedIn; hh.ru' },
  // WAREHOUSE / LOGISTICS / RETAIL
  { company_name: 'Magnit (Магнит)', domain: 'magnit.ru', sector: 'retail', priority: 'HIGH', city: 'Krasnodar', region: 'National', company_size: '300,000+', pain_point: 'Russia largest retailer. 36+ distribution centers all critically understaffed.', decision_maker_title: 'Директор по массовому найму', phone: '+7 861 210 9810', email: 'hr@magnit.ru', contact_method: 'Email', find_instructions: 'magnit.ru/career; LinkedIn; hh.ru' },
  { company_name: 'Yandex Market / Yandex Logistics', domain: 'market.yandex.ru', sector: 'warehouse_logistics', priority: 'HIGH', city: 'Moscow', region: 'Moscow', company_size: '10,000+', pain_point: 'Rapid fulfillment center expansion. Competing with Ozon and Wildberries.', decision_maker_title: 'HR Director', phone: '+7 495 739 7000', email: 'jobs@yandex-team.ru', contact_method: 'Email + LinkedIn', find_instructions: 'yandex.ru/jobs; LinkedIn; hh.ru' },
  { company_name: 'FM Logistic Russia', domain: 'fmlogistic.ru', sector: 'warehouse_logistics', priority: 'HIGH', city: 'Moscow', region: 'Moscow + Regions', company_size: '5,000+', pain_point: 'French contract logistics. 1M+ sqm of warehouses. Always hiring.', decision_maker_title: 'HR Director', phone: '+7 499 922 2233', email: 'hr@fmlogistic.ru', contact_method: 'Email', find_instructions: 'fmlogistic.ru/contacts; LinkedIn; hh.ru' },
  // FOOD PROCESSING
  { company_name: 'Miratorg (Мираторг)', domain: 'miratorg.ru', sector: 'food_processing', priority: 'HIGH', city: 'Moscow', region: 'Moscow + Belgorod', company_size: '30,000+', pain_point: 'Russia largest meat producer. Extreme labor demand.', decision_maker_title: 'Директор по персоналу', phone: '+7 495 363 2401', email: 'hr@miratorg.ru', contact_method: 'Email', find_instructions: 'miratorg.ru/contacts; LinkedIn; hh.ru' },
  { company_name: 'Cherkizovo Group', domain: 'cherkizovo.com', sector: 'food_processing', priority: 'HIGH', city: 'Moscow', region: 'Moscow', company_size: '20,000+', pain_point: 'One of Russia largest meat producers. Multiple processing facilities nationwide.', decision_maker_title: 'HR Director', phone: '+7 495 788 7878', email: 'hr@cherkizovo.com', contact_method: 'Email', find_instructions: 'cherkizovo.com/contacts; LinkedIn; hh.ru' },
  // AGENCY PARTNERS
  { company_name: 'ANCOR Russia', domain: 'ancor.ru', sector: 'agency_partner', priority: 'HIGH', city: 'Moscow', region: 'National', company_size: '1,000+', pain_point: 'Russia largest staffing agency. Partnership = access to entire client base.', decision_maker_title: 'Business Development Director', phone: '+7 495 796 0444', email: 'info@ancor.ru', contact_method: 'Email + LinkedIn', find_instructions: 'ancor.ru/contacts; LinkedIn; VK', notes: 'PARTNER opportunity — structure as supply agreement.' },
  { company_name: 'Kelly Services Russia', domain: 'kellyservices.ru', sector: 'agency_partner', priority: 'HIGH', city: 'Moscow', region: 'Moscow', company_size: '500+', pain_point: 'International staffing agency. Partnership = supply Indian workers to their corporate clients.', decision_maker_title: 'Country Director', phone: '+7 495 725 1818', email: 'info@kellyservices.ru', contact_method: 'Email + LinkedIn', find_instructions: 'kellyservices.ru/contacts; VK; LinkedIn', notes: 'PARTNER — structured as supply agreement.' },
  // INDUSTRY ASSOCIATIONS
  { company_name: 'Ural Chamber of Commerce (УППУ)', domain: 'uralcci.ru', sector: 'industry_association', priority: 'HOT', city: 'Yekaterinburg', region: 'Sverdlovsk Region', company_size: 'Organization', pain_point: 'President Andrei Besedin EXPLICITLY called for Indian workers. Warm lead.', decision_maker_title: 'Besedin Office / International Relations', phone: '+7 343 214 8787', email: 'info@uralcci.ru', contact_method: 'Phone (call today)', find_instructions: 'uralcci.ru/contacts; LinkedIn', notes: 'WARM LEAD — they publicly asked for Indian workers. Call today.' },
  { company_name: 'RSPP (Russian Union of Industrialists)', domain: 'rspp.ru', sector: 'industry_association', priority: 'HOT', city: 'Moscow', region: 'Moscow', company_size: 'Organization', pain_point: 'Most powerful Russian business lobby. Getting in = access to every major factory owner in Russia.', decision_maker_title: 'International Relations Committee', phone: '+7 495 628 0022', email: 'info@rspp.ru', contact_method: 'Email', find_instructions: 'rspp.ru/contacts; LinkedIn', notes: 'Association introduction = instant credibility with every major factory.' },
  { company_name: 'HeadHunter (hh.ru) B2B Team', domain: 'hh.ru', sector: 'agency_partner', priority: 'HOT', city: 'Moscow', region: 'Moscow', company_size: '2,000+', pain_point: 'hh.ru has 1M+ employer accounts. Get featured in their HR manager newsletter.', decision_maker_title: 'B2B Partnership / Employer Solutions', phone: '+7 495 974 6434', email: 'b2b@hh.ru', contact_method: 'Email', find_instructions: 'hh.ru/employer; LinkedIn hh.ru B2B', notes: 'Platform partnership = massive reach.' },
  // PORTS / LOGISTICS
  { company_name: 'Port of Novorossiysk (НМТП)', domain: 'ncsp.ru', sector: 'warehouse_logistics', priority: 'HIGH', city: 'Novorossiysk', region: 'Krasnodar Region', company_size: '8,000+', pain_point: 'Russia largest commercial port. Loaders, dock workers, freight handlers.', decision_maker_title: 'HR Director', phone: '+7 8617 60 3000', email: 'hr@ncsp.ru', contact_method: 'Phone + Email', find_instructions: 'ncsp.ru/contacts; hh.ru; 2GIS Novorossiysk' },
  { company_name: 'Port of Vladivostok (FESCO)', domain: 'fesco.ru', sector: 'warehouse_logistics', priority: 'HIGH', city: 'Vladivostok', region: 'Primorsky Region', company_size: '5,000+', pain_point: 'Far East Russia largest port. Extreme labor shortage in region.', decision_maker_title: 'HR Department', phone: '+7 4232 60 5020', email: 'hr@fesco.ru', contact_method: 'Phone', find_instructions: 'fesco.ru/contacts; hh.ru Vladivostok', notes: 'Far East + port = double shortage. Premium fees possible.' },
  // MANUFACTURING
  { company_name: 'Technonicol (ТехноНИКОЛЬ)', domain: 'technonicol.ru', sector: 'manufacturing', priority: 'HIGH', city: 'Moscow', region: '50 plants nationwide', company_size: '20,000+', pain_point: 'Russia largest insulation/roofing manufacturer. 50 plants all need workers.', decision_maker_title: 'Group HR Director', phone: '+7 495 748 9800', email: 'hr@technonicol.ru', contact_method: 'Email + LinkedIn', find_instructions: 'technonicol.ru/contacts; LinkedIn; hh.ru', notes: 'Manufacturing line workers across Russia. Huge scale.' },
  { company_name: 'Vladivostok Shipyard Zvezda', domain: 'zvezda-ru.ru', sector: 'manufacturing', priority: 'HIGH', city: 'Vladivostok', region: 'Primorsky Region (Far East)', company_size: '7,000+', pain_point: 'New major shipyard expanding. Far East Russia desperately needs workers.', decision_maker_title: 'HR Manager', phone: '+7 4232 26 6060', email: 'hr@zvezda-ru.ru', contact_method: 'Phone', find_instructions: 'zvezda-ru.ru; hh.ru Vladivostok', notes: 'Far East = highest labor shortage region. Premium contracts possible.' },
  { company_name: 'Nord Gold / Nordgold', domain: 'nordgold.com', sector: 'mining', priority: 'HIGH', city: 'Moscow', region: 'Remote Russia', company_size: '8,000+', pain_point: 'Gold mining in remote Russian regions. Constant worker shortage at mine sites.', decision_maker_title: 'HR Director', phone: '+7 495 795 4567', email: 'hr@nordgold.com', contact_method: 'Email + LinkedIn', find_instructions: 'nordgold.com/en/contacts; LinkedIn; hh.ru' },
  { company_name: 'EVRAZ Russia', domain: 'evraz.com', sector: 'metallurgy', priority: 'HIGH', city: 'Moscow', region: 'Multiple (Ural/Siberia)', company_size: '30,000+', pain_point: 'Major steel and mining. Operations in Nizhny Tagil, Novokuznetsk — very hard to staff.', decision_maker_title: 'HR Director', phone: '+7 495 232 1370', email: 'hr@evraz.com', contact_method: 'Email + LinkedIn', find_instructions: 'evraz.com/en/contacts; LinkedIn; hh.ru' },
  { company_name: 'Tatarstan Chamber of Commerce', domain: 'tpprt.ru', sector: 'industry_association', priority: 'HIGH', city: 'Kazan', region: 'Tatarstan', company_size: 'Organization', pain_point: 'Tatarstan industrial republic. Very active business community. Receptive to foreign partnerships.', decision_maker_title: 'International Cooperation Department', phone: '+7 843 236 7800', email: 'info@tpprt.ru', contact_method: 'Email + Phone', find_instructions: 'tpprt.ru/contacts' },
  { company_name: 'Trudemigrant.ru Portal', domain: 'trudemigrant.ru', sector: 'agency_partner', priority: 'HIGH', city: 'Online', region: 'Russia', company_size: 'Platform', pain_point: 'Portal serving companies that need foreign workers. Listing = ongoing inbound leads.', decision_maker_title: 'Content / Partnership Team', contact_method: 'Email', find_instructions: 'trudemigrant.ru contact form', notes: 'Platform listing = passive inbound. Priority quick win.' },
  { company_name: 'Far East Construction Projects (batch)', sector: 'construction', priority: 'HOT', city: 'Vladivostok', region: 'Primorsky/Khabarovsk Region', company_size: 'Variable', pain_point: 'Most extreme labor shortage in Russia. Any construction company there is desperate.', decision_maker_title: 'Project Director / HR', contact_method: 'Telegram DM + Phone', find_instructions: 'hh.ru Vladivostok; 2GIS; Telegram groups Far East construction', notes: 'Far East = highest urgency. Premium fees possible.' },
];

async function run() {
  let added = 0, skipped = 0;
  for (const lead of LEADS) {
    const dk = dedupKey(lead.company_name, lead.domain);
    const exists = await pool.query('SELECT id FROM gtm_leads WHERE dedup_key = $1', [dk]);
    if (exists.rows.length) { skipped++; continue; }
    try {
      await pool.query(
        `INSERT INTO gtm_leads (company_name, domain, sector, priority, status, city, region, company_size, pain_point, decision_maker_title, phone, email, contact_method, find_instructions, notes, scraped_from, dedup_key, country) VALUES ($1,$2,$3,$4,'not_contacted',$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,'seed',$15,'Russia')`,
        [lead.company_name, lead.domain||'', lead.sector, lead.priority, lead.city||'', lead.region||'', lead.company_size||'', lead.pain_point||'', lead.decision_maker_title||'', lead.phone||'', lead.email||'', lead.contact_method||'', lead.find_instructions||'', lead.notes||'', dk]
      );
      added++;
    } catch (e) {
      if (e.message?.includes('duplicate') || e.message?.includes('unique')) skipped++;
      else console.error('Error:', lead.company_name, e.message);
    }
  }
  console.log(`\n✅ Seeded ${added} leads, ${skipped} already existed (${LEADS.length} total)`);
  await pool.end();
}

run().catch(e => { console.error(e); process.exit(1); });
